import type { Review } from './types.ts'

export const reviews: Review[] = [
  {
    id: 'r-1041',
    name: 'Marisol T.',
    city: 'Austin',
    rating: 5,
    date: '2026-06-30',
    source: 'Google',
    serviceSlug: 'electrical-panel-upgrades',
    featured: true,
    text: 'Our inspection flagged a Federal Pacific panel eight days before closing and our lender would not fund without it replaced. Hill Country pulled the permit the next morning, coordinated the Austin Energy disconnect, and had the closed permit to our title company with two days to spare. Diego explained exactly what he found behind the old panel, including some scorched wire nobody had mentioned. We closed on time.',
  },
  {
    id: 'r-1039',
    name: 'Kevin R.',
    city: 'Round Rock',
    rating: 5,
    date: '2026-06-22',
    source: 'Google',
    serviceSlug: 'ev-charger-installation',
    featured: true,
    text: 'Two other companies told me I needed a $4,000 service upgrade to add a second charger. These guys pulled my actual usage data, showed me the numbers, and installed a load-sharing pair on my existing 150-amp service instead. Both cars charge overnight without an issue. They talked themselves out of a much bigger job and I will call nobody else now.',
    response: 'Thanks Kevin. Metered demand almost always comes in lower than a worst-case calculated load — it is worth checking before anyone quotes a service upgrade.',
  },
  {
    id: 'r-1036',
    name: 'Dana W.',
    city: 'Austin',
    rating: 5,
    date: '2026-05-17',
    source: 'Google',
    serviceSlug: 'emergency-electrical-repair',
    featured: true,
    text: 'A limb came down during the storm and ripped the mast off the side of our house at about 9pm. There were live wires hanging in the back yard with two kids in the house. Someone answered on the second ring, told me exactly which area to keep everyone away from, and a truck was here in under an hour. They rebuilt the mast and meter base overnight and the utility reconnected before 5am.',
  },
  {
    id: 'r-1034',
    name: 'Priya N.',
    city: 'Austin',
    rating: 5,
    date: '2026-05-04',
    source: 'Google',
    serviceSlug: 'lighting-installation',
    featured: true,
    text: 'They taped out every recessed light position on the ceiling and walked it with me before cutting a single hole. I moved two of them and I am glad I did. The under-cabinet lighting is completely hidden and the whole kitchen finally reads as one consistent color instead of the yellow-and-blue mix we had before. No flicker on the dimmer at any level.',
  },
  {
    id: 'r-1031',
    name: 'Gerald M.',
    city: 'Round Rock',
    rating: 5,
    date: '2026-04-11',
    source: 'Facebook',
    serviceSlug: 'whole-home-rewiring',
    featured: true,
    text: 'Two contractors quoted me a $22,000 rewire because of aluminum wiring. Hill Country came out, opened boxes, and told me the aluminum itself was fine — it was the terminations. They pigtailed all 94 devices with listed connectors for a fraction of that and put together the documentation my insurance company needed. Honest people.',
  },
  {
    id: 'r-1029',
    name: 'Beth A.',
    city: 'Cedar Park',
    rating: 5,
    date: '2026-03-28',
    source: 'Google',
    serviceSlug: 'electrical-panel-upgrades',
    featured: false,
    text: 'Our solar installer put in the panels and battery but left the backup design half finished. Hill Country built a critical-load sub-panel and moved exactly the circuits that matter — fridge, well pump, network, one AC zone. During the outage in June we ran for two days without thinking about it.',
  },
  {
    id: 'r-1027',
    name: 'Tomás L.',
    city: 'Austin',
    rating: 5,
    date: '2026-03-15',
    source: 'Google',
    serviceSlug: 'circuit-breaker-repair',
    featured: false,
    text: 'Our kitchen breaker had been tripping for months and the last electrician just replaced the breaker, which changed nothing. These guys put a clamp meter on it, had my wife run the microwave and the toaster like we normally do, and showed me the circuit was pulling 22 amps on a 20-amp breaker. They moved the microwave to its own circuit. Problem gone. It took an hour.',
  },
  {
    id: 'r-1025',
    name: 'Sandra K.',
    city: 'Georgetown',
    rating: 5,
    date: '2026-02-27',
    source: 'Google',
    serviceSlug: 'generator-installation',
    featured: false,
    text: 'We are in Sun City and lost power three times in eighteen months. The generator install took longer than I expected, but they explained up front that the gas line and permits were the slow part and they were right about the timeline to the week. They came back and walked me through the app twice because I asked. It has already run twice on its own.',
  },
  {
    id: 'r-1023',
    name: 'Michael B.',
    city: 'Lakeway',
    rating: 5,
    date: '2026-02-20',
    source: 'Google',
    serviceSlug: 'generator-installation',
    featured: false,
    text: 'Three AC systems, a well and a pool. Every other bid pushed me toward a bigger, louder generator. Hill Country worked out a start delay on the third compressor so a 26kW unit handles the whole house. They also handled the HOA package with a sound study and it was approved without a hearing.',
  },
  {
    id: 'r-1021',
    name: 'Alicia F.',
    city: 'Austin',
    rating: 4,
    date: '2026-02-09',
    source: 'Yelp',
    serviceSlug: 'ceiling-fan-installation',
    featured: false,
    text: 'Good work on four fans including two on a vaulted ceiling. The only reason this is not five stars is that the first appointment got pushed a day because of an emergency call ahead of me. They called well in advance and knocked something off the price without me asking, which I appreciated. The fans are dead silent.',
    response: 'Fair, Alicia — an emergency ahead of you is still a delay for you. Thanks for the patience and for the honest review.',
  },
  {
    id: 'r-1019',
    name: 'Ryan H.',
    city: 'Pflugerville',
    rating: 5,
    date: '2026-01-30',
    source: 'Google',
    serviceSlug: 'ev-charger-installation',
    featured: false,
    text: 'Clean conduit run, mounted at a height where the cable actually reaches without being stretched, and they verified a full-rate charge session before leaving. They also filled out the Austin Energy rebate form for me and told me exactly what to submit. Small thing, but it saved me an evening.',
  },
  {
    id: 'r-1017',
    name: 'Joanne P.',
    city: 'Austin',
    rating: 5,
    date: '2026-01-18',
    source: 'Nextdoor',
    serviceSlug: 'electrical-inspections',
    featured: false,
    text: 'We were about to buy a 1958 house in Allandale. The general inspector wrote one line about the panel. Hill Country spent two hours, found an unpermitted sub-panel in the garage and a junction box buried in a wall with no cover, and gave us a photographed report with cost ranges. We used it to negotiate $9,000 off. Best $329 we spent on that purchase.',
  },
  {
    id: 'r-1015',
    name: 'Carlos D.',
    city: 'Austin',
    rating: 5,
    date: '2025-12-14',
    source: 'Google',
    serviceSlug: 'commercial-electrical',
    featured: false,
    text: 'They did the full electrical for our restaurant on South Congress. Our equipment package changed twice mid-build and they absorbed it without a change order both times because they had built spare capacity into the design. We opened on our lease date. In this business that is everything.',
  },
  {
    id: 'r-1013',
    name: 'Nina S.',
    city: 'Austin',
    rating: 5,
    date: '2025-12-02',
    source: 'Google',
    serviceSlug: 'whole-home-rewiring',
    featured: false,
    text: 'They rewired our 1926 Hyde Park bungalow in three stages so we always had a working kitchen and bathroom with a newborn in the house. They removed the old knob-and-tube instead of abandoning it in the attic, and they brought in someone who could actually match 100-year-old plaster. Eleven days, and the house looks untouched.',
  },
  {
    id: 'r-1011',
    name: 'Wes O.',
    city: 'Buda',
    rating: 5,
    date: '2025-11-19',
    source: 'Google',
    serviceSlug: 'new-construction-wiring',
    featured: false,
    text: 'Ran a feeder 280 feet out to my shop. They sized the wire for voltage drop rather than the minimum, which cost a little more up front. My welder strikes clean and the lights do not dip when the compressor kicks on. Worth it.',
  },
  {
    id: 'r-1009',
    name: 'Hannah G.',
    city: 'Kyle',
    rating: 5,
    date: '2025-11-06',
    source: 'Google',
    serviceSlug: 'outlet-and-switch-installation',
    featured: false,
    text: 'Added six outlets, including two outside with proper in-use covers, and replaced every two-prong outlet in the older part of the house. The electrician explained why the outdoor ones needed a different device than the indoor ones instead of just doing it. Cuts in the drywall were small and clean.',
  },
  {
    id: 'r-1007',
    name: 'Derek V.',
    city: 'Austin',
    rating: 5,
    date: '2025-10-21',
    source: 'Google',
    serviceSlug: 'smoke-and-co-detectors',
    featured: false,
    text: 'Turns out every alarm in our house was eleven years old and two bedrooms had none at all. They replaced everything with interconnected units and one of them is a combination CO unit near the garage. Then they set one off to prove the whole house sounds together. Should have done this years ago.',
  },
  {
    id: 'r-1005',
    name: 'Lauren M.',
    city: 'Austin',
    rating: 5,
    date: '2025-10-08',
    source: 'Google',
    serviceSlug: 'smart-home-electrical',
    featured: false,
    text: 'I had a drawer full of smart switches that would not power on. They opened three boxes, showed me there was no neutral in any of them, and gave me two options with real prices instead of telling me it was impossible. Pulled neutrals to five boxes, used no-neutral devices elsewhere, and left me a printed map of what controls what.',
  },
  {
    id: 'r-1003',
    name: 'Anthony C.',
    city: 'Cedar Park',
    rating: 5,
    date: '2025-09-25',
    source: 'Google',
    serviceSlug: 'surge-protection',
    featured: false,
    text: 'Lost a TV and a router in a storm last year. They checked the grounding first and found we only had one ground rod and no water bond — then installed the surge protector. He was clear that the device would have been close to useless without fixing the ground first. Appreciated the explanation.',
  },
  {
    id: 'r-1001',
    name: 'Rebecca J.',
    city: 'Georgetown',
    rating: 5,
    date: '2025-09-11',
    source: 'Google',
    serviceSlug: 'lighting-installation',
    featured: false,
    text: 'Landscape lighting across a sloped lot in Old Town. They aimed every fixture with me after dark rather than setting it up at noon and leaving. Transformer is sized with room to add more later, which they suggested without upselling me on fixtures I did not need yet.',
  },
]
