import type { TeamMember } from './types.ts'

const photo = (slug: string, name: string, role: string) => ({
  src: `/images/team/${slug}.svg`,
  alt: `${name}, ${role} at Hill Country Electric`,
  width: 600,
  height: 600,
})

export const team: TeamMember[] = [
  {
    slug: 'ray-alvarado',
    name: 'Ray Alvarado',
    role: 'Owner & Master Electrician',
    photo: photo('ray-alvarado', 'Ray Alvarado', 'Owner and Master Electrician'),
    bio: 'Ray started as an apprentice in 1998 pulling wire on commercial jobs in San Antonio, got his master license in 2007, and opened Hill Country Electric out of a single truck in 2009. He still runs the load calculations on every panel and service upgrade the company quotes. If you get a written recommendation for 150 amps instead of 200, Ray is the reason.',
    certifications: ['Texas Master Electrician', 'NFPA 70E Arc Flash Safety', 'Generac Certified Installer'],
    licenseInfo: 'Master Electrician License ME 21874 · Contractor License TECL 34291',
    yearsExperience: 28,
    specialties: ['Service and panel design', 'Load calculations', 'Historic home rewiring'],
  },
  {
    slug: 'diego-serrano',
    name: 'Diego Serrano',
    role: 'Service Manager & Journeyman Electrician',
    photo: photo('diego-serrano', 'Diego Serrano', 'Service Manager and Journeyman Electrician'),
    bio: 'Diego runs the residential service side and takes most of the calls that start with "something smells hot." He is the one who will walk you through shutting off the right breaker at midnight. He has a particular talent for troubleshooting intermittent faults — the ones that never happen while an electrician is standing there.',
    certifications: ['Texas Journeyman Electrician', 'Infrared Thermography Level I', 'NFPA 70E Arc Flash Safety'],
    licenseInfo: 'Journeyman License JM 108442',
    yearsExperience: 14,
    specialties: ['Diagnostics and troubleshooting', 'Emergency response', 'Thermal imaging'],
  },
  {
    slug: 'monica-reyes',
    name: 'Monica Reyes',
    role: 'Project Manager',
    photo: photo('monica-reyes', 'Monica Reyes', 'Project Manager'),
    bio: 'Monica handles permits, inspections, scheduling and the Austin Energy coordination that makes or breaks a panel upgrade timeline. If your project has a closing date attached to it, she is the person who builds the schedule backward from it. She has been doing Austin permit work long enough to know which submissions get held up and why.',
    certifications: ['OSHA 30-Hour Construction', 'City of Austin permitting'],
    yearsExperience: 11,
    specialties: ['Permits and inspections', 'Utility coordination', 'Commercial finish-out scheduling'],
  },
  {
    slug: 'travis-boyd',
    name: 'Travis Boyd',
    role: 'Commercial Lead Electrician',
    photo: photo('travis-boyd', 'Travis Boyd', 'Commercial Lead Electrician'),
    bio: 'Travis runs the commercial crew — restaurant and retail finish-outs, three-phase distribution, and the overnight work that lets a business open the next morning as if nothing happened. He came up through industrial work, which is why our commercial panel rooms tend to look better than they have to.',
    certifications: ['Texas Journeyman Electrician', 'NFPA 70E Arc Flash Safety', 'OSHA 30-Hour Construction'],
    licenseInfo: 'Journeyman License JM 96310',
    yearsExperience: 17,
    specialties: ['Three-phase distribution', 'Tenant finish-out', 'Kitchen equipment circuits'],
  },
  {
    slug: 'sam-okafor',
    name: 'Sam Okafor',
    role: 'Journeyman Electrician',
    photo: photo('sam-okafor', 'Sam Okafor', 'Journeyman Electrician'),
    bio: 'Sam does most of our EV charger and smart home work. He is the one who will open three switch boxes before recommending any hardware, because the fastest way to waste a homeowner’s money is to install devices the wiring cannot support. He leaves a printed map of every smart system he sets up.',
    certifications: ['Texas Journeyman Electrician', 'EVITP Certified (EV Infrastructure Training)', 'Lutron Certified Installer'],
    licenseInfo: 'Journeyman License JM 121905',
    yearsExperience: 9,
    specialties: ['EV charging', 'Smart home and lighting control', 'Load management systems'],
  },
  {
    slug: 'grace-whitfield',
    name: 'Grace Whitfield',
    role: 'Journeyman Electrician',
    photo: photo('grace-whitfield', 'Grace Whitfield', 'Journeyman Electrician'),
    bio: 'Grace works primarily on rewires and older homes, which means a lot of time in Hyde Park attics and Georgetown crawl spaces. She has the patience for knob-and-tube removal that most people do not, and she is meticulous about fishing runs without opening walls that do not need opening.',
    certifications: ['Texas Journeyman Electrician', 'Lead-Safe Renovator (RRP)', 'NFPA 70E Arc Flash Safety'],
    licenseInfo: 'Journeyman License JM 114077',
    yearsExperience: 8,
    specialties: ['Whole-home rewiring', 'Historic and pre-war homes', 'Minimal-damage cable fishing'],
  },
  {
    slug: 'noah-kim',
    name: 'Noah Kim',
    role: 'Apprentice Electrician',
    photo: photo('noah-kim', 'Noah Kim', 'Apprentice Electrician'),
    bio: 'Noah is in his third year of a four-year apprenticeship and rides with Diego on service calls. He is the reason our trucks are actually organized. He will be sitting his journeyman exam next year.',
    certifications: ['Texas Electrical Apprentice', 'OSHA 10-Hour Construction'],
    licenseInfo: 'Apprentice Registration AP 208833',
    yearsExperience: 3,
    specialties: ['Service work', 'Lighting installation', 'Device replacement'],
  },
  {
    slug: 'karen-doyle',
    name: 'Karen Doyle',
    role: 'Office Manager',
    photo: photo('karen-doyle', 'Karen Doyle', 'Office Manager'),
    bio: 'Karen is usually the first person you talk to. She schedules the trucks, tracks the same-day slots, and is the one who calls you when a job ahead of yours is running long. She has been with Ray since the company had two employees.',
    certifications: [],
    yearsExperience: 15,
    specialties: ['Scheduling', 'Estimates and invoicing', 'Warranty claims'],
  },
]
